kind: Deployment
apiVersion: apps/v1
metadata:
  name: qledger
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qledger

  template:
    metadata:
      labels:
        app: qledger
    spec:
      containers:
      - name: qledger
        image: bprofitt/qledger:latest
        ports:
        - containerPort: 7000

kind: Service
apiVersion: v1

metadata:
  name: qledger-elb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: LoadBalancer
  selector:
    app: qledger
  ports:
    - name: http
      port: 80
      targetPort: 7000

